// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5YveTa8v1Mk8TGzX6gFVqK8u4m22YDMs',
    appId: '1:761369303237:web:2ab07972c4801a9e0ef8ac',
    messagingSenderId: '761369303237',
    projectId: 'lenussuperapp',
    authDomain: 'lenussuperapp.firebaseapp.com',
    storageBucket: 'lenussuperapp.firebasestorage.app',
    measurementId: 'G-9TCP4DN8NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUxrQiqoQ_qIahSvTLK307DjtJXJ7Rss',
    appId: '1:761369303237:android:1206528090abacbd0ef8ac',
    messagingSenderId: '761369303237',
    projectId: 'lenussuperapp',
    storageBucket: 'lenussuperapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsgh7dl1u0XHhasvafl9o1iH5ncKc4PC4',
    appId: '1:761369303237:ios:2f34c51c409d44390ef8ac',
    messagingSenderId: '761369303237',
    projectId: 'lenussuperapp',
    storageBucket: 'lenussuperapp.firebasestorage.app',
    iosBundleId: 'com.example.lenus1',
  );

}